"""
语言管理模块
负责管理应用的语言设置（中文/英文）
"""
import json
import os
from pathlib import Path
from typing import Dict, Any, Optional

# 语言配置文件路径
LANGUAGE_CONFIG_FILE = Path("config/language.json")

# 默认语言
DEFAULT_LANGUAGE = "zh"

# 语言文本字典
LANGUAGE_TEXTS = {
    "zh": {
        # 通用
        "loading": "加载中...",
        "save": "保存",
        "cancel": "取消",
        "delete": "删除",
        "edit": "编辑",
        "add": "新增",
        "close": "关闭",
        "confirm": "确认",
        "test": "测试",
        "success": "成功",
        "error": "错误",
        "warning": "警告",
        
        # 侧边栏
        "sidebar_title": "BI Platform",
        "datasource_management": "数据源管理",
        "chart_designer": "图表设计器",
        "dashboard": "仪表盘",
        "settings": "设置",
        "version": "版本",
        "ui_only": "仅 UI 界面",
        
        # 设置页面
        "general_settings": "通用设置",
        "auto_refresh_interval": "自动刷新间隔",
        "off": "关闭",
        "minutes": "分钟",
        "hour": "小时",
        "default_chart_theme": "默认图表主题",
        "default": "默认",
        "business_blue": "商务蓝",
        "vibrant_orange": "活力橙",
        "natural_green": "自然绿",
        "purple": "优雅紫",
        "save_settings": "保存设置",
        "settings_saved": "设置已保存成功！",
        "datasource_config": "数据源配置",
        "export_config": "导出配置",
        "export_all_datasource_config": "导出所有数据源配置",
        "import_config": "导入配置",
        "import_datasource_config": "导入数据源配置",
        "language_settings": "语言设置",
        "select_language": "选择语言",
        "chinese": "中文",
        "english": "English",
        "language_changed": "语言已切换成功！",
        
        # 数据源页面
        "datasource_management_title": "数据源管理",
        "datasource_list": "数据源列表",
        "add_datasource": "+ 新增数据源",
        "upload_file": "上传文件",
        "upload_file_button": "上传文件",
        "supported_formats": "支持 CSV、Excel (.xls, .xlsx)",
        "datasource_name": "数据源名称",
        "datasource_name_placeholder": "例如: 销售数据",
        "local_file": "本地文件 (CSV/Excel)",
        "database": "数据库",
        "rest_api": "REST API",
        "database_type": "数据库类型",
        "database_host": "主机地址",
        "database_port": "端口",
        "database_name": "数据库名",
        "database_user": "用户名",
        "database_password": "密码",
        "sql_query": "SQL 查询",
        "table_name": "表名",
        "api_url": "API 地址",
        "request_method": "请求方法",
        "api_headers": "请求头 (JSON 格式)",
        "api_params": "请求参数 (JSON 格式)",
        "api_name_placeholder": "例如: API 数据源",
        "database_name_placeholder": "例如: 生产数据库",
        "test_connection": "测试连接",
        "connection_success": "连接成功！",
        "connection_failed": "连接失败",
        "api_connection_success": "API 连接成功！",
        "fill_api_url": "请填写 API 地址",
        "invalid_json_format": "格式错误，请输入有效的 JSON",
        "headers_format_error": "请求头格式错误，请输入有效的 JSON",
        "params_format_error": "请求参数格式错误，请输入有效的 JSON",
        "no_datasource": "暂无数据源，请点击 '新增数据源' 添加",
        "connected": "已连接",
        "disconnected": "未连接",
        "data_preview": "数据预览",
        "select_datasource_for_preview": "请选择一个数据源查看预览",
        "edit_datasource": "编辑数据源",
        "new_datasource": "新增数据源",
        "upload_success": "文件上传成功！",
        "fill_database_info": "请填写完整的数据库信息",
        "upload_file_first": "请先上传文件",
        "data_rows_cols": "数据量：{} 行 × {} 列",
        "fields": "字段：{}",
        "filename": "文件名",
        "field_info": "字段信息",
        "field_type_numeric": "数值",
        "field_type_date": "日期",
        "field_type_text": "文本",
        "operation_failed": "操作失败",
        "datasource_saved": "数据源保存成功！",
        "datasource_deleted": "数据源已删除",
        "preview_failed": "预览失败",
        "operation_id_parse_failed": "操作标识解析失败",
        "name": "名称",
        "type": "类型",
        "status": "状态",
        "last_updated": "最后更新",
        "actions": "操作",
        "database_tab_label": "数据库 (PostgreSQL/MySQL)",
        
        # 图表设计器页面
        "chart_designer_title": "图表设计器",
        "select_datasource": "选择数据源",
        "field_list": "字段列表（可拖拽）",
        "select_datasource_first": "请选择数据源后查看字段",
        "chart_type": "图表类型",
        "line_chart": "折线图",
        "bar_chart": "柱状图",
        "pie_chart": "饼图",
        "table": "表格",
        "combo_chart": "组合图",
        "chart_config": "图表配置",
        "x_axis": "X 轴",
        "y_axis": "Y 轴",
        "group": "分组",
        "chart_title": "图表标题",
        "color_theme": "颜色主题",
        "show_labels": "显示数据标签",
        "show_legend": "显示图例",
        "aggregation_function": "聚合函数",
        "preview": "预览",
        "save_chart": "保存图表",
        "clear": "清空",
        "drag_field_here": "拖拽字段到此处",
        "display_orientation": "展示方向",
        "horizontal_display": "横向展示（字段为列）",
        "vertical_display": "纵向展示（字段为行）",
        "table_columns_config": "表格列配置",
        "drag_field_to_columns": "拖拽字段到下方列区域以设置表格列",
        "drag_field_as_column": "拖拽字段到此处作为第{}列",
        "add_column": "添加列",
        "table_rows_config": "表格行配置",
        "drag_field_to_rows": "拖拽字段到下方行区域以设置表格行",
        "drag_field_as_row": "拖拽字段到此处作为第{}行",
        "add_row": "添加行",
        "group_color": "分组/颜色",
        "aggregation_function_config": "聚合函数配置",
        "default_aggregation_function": "默认聚合函数（所有Y轴字段）",
        "field_aggregation_function": "各字段聚合函数（可选）",
        "field_aggregation_hint": "可以为每个Y轴字段单独设置聚合函数。如果不设置，将使用默认聚合函数。",
        "sum": "求和 (SUM)",
        "avg": "平均值 (AVG)",
        "count": "计数 (COUNT)",
        "max": "最大值 (MAX)",
        "min": "最小值 (MIN)",
        "percentage": "占比 (Percentage)",
        "style_config": "样式配置",
        "enter_chart_title": "请输入图表标题",
        "custom_color_config": "自定义颜色（每个分组使用不同颜色）",
        "custom_color_hint": "当有分组字段时，可以为每个分组设置自定义颜色。颜色将自动确保不重复。",
        "set_group_field_first": "请先设置分组字段",
        "saved_charts": "已保存图表",
        "refresh": "刷新",
        "chart_preview": "图表预览",
        "export_image": "导出图片",
        "select_datasource_and_config": "请选择数据源并配置字段以生成预览",
        "no_saved_charts": "暂无已保存的图表",
        "unknown": "未知",
        "chart_type_colon": "类型: {}",
        "created_colon": "创建: {}",
        "unnamed_chart": "未命名图表",
        "chart": "图表",
        "drag_field_to_x_axis": "请将字段拖拽到 X 轴",
        "add_y_axis_field_first": "请先添加Y轴字段",
        "at_least_one_y_axis": "请至少选择一个 Y 轴字段",
        "pie_needs_group_field": "饼图需要分组字段",
        "pie_needs_numeric_field": "饼图需要一个数值字段",
        "data_table": "数据表格",
        "chart_saved_success": "图表保存成功！",
        "save_chart_failed": "保存图表失败",
        "new_chart_created": "已创建新图表，请开始配置",
        "hint_drag_field_below": "提示：拖拽字段到下方区域",
        "numeric_field_required": "数值字段（必需）",
        "hint_drag_numeric_field": "提示：拖拽数值字段到下方区域",
        "category_field_required": "分类字段（必需）",
        "hint_drag_category_field": "提示：拖拽分类字段到下方区域",
        "y_axis_label": "Y 轴",
        "group_color_label": "分组/颜色",
        "select_datasource_to_view_fields": "请选择数据源后查看字段",
        "select_datasource": "请选择数据源",
        "drag_field_to_table_columns": "请拖拽字段到表格列区域",
        "drag_field_to_table_rows": "请拖拽字段到表格行区域",
        "field_not_in_data": "所选字段不存在于数据中",
        "generate_chart_failed": "生成图表失败",
        "select_datasource_first": "请先选择数据源",
        "please_add_datasource_first": "请先添加数据源",
        "loading": "加载中...",
        "filter_mode": "筛选模式",
        "drill_down_mode": "下钻模式",
        "current_mode_filter": "当前模式：筛选模式 - 左键点击图表数据点可筛选其他图表",
        "current_mode_drill_down": "当前模式：下钻模式 - 左键点击图表数据点可查看详细数据",
        "filter_source": "筛选源",
        "filtered": "已筛选: {}={}",
        "filtering": "筛选中: {} - {}={}",
        "time_filter_no_data": "时间筛选后无数据（筛选字段: {}）",
        "clear_filter": "清除筛选",
        "share_link": "分享链接",
        "all": "全部",
        "start_date": "起始日期",
        "end_date": "结束日期",
        "please_select_or_create_dashboard": "请选择或创建一个仪表盘",
        "new_dashboard": "新建仪表盘",
        "enter_dashboard_name": "请输入仪表盘名称",
        "enter_description_optional": "请输入描述（可选）",
        "add_chart_to_dashboard": "添加图表到仪表盘",
        "select_chart": "选择图表",
        "share_dashboard_link": "分享仪表盘链接",
        "copy_link_to_share": "复制下面的链接分享给其他人，他们可以直接访问此仪表盘：",
        "copy": "复制",
        "tip": "提示：",
        "share_link_tip": "分享的链接包含当前仪表盘的ID，访问者将看到相同的仪表盘内容。",
        "no_charts_in_dashboard": "该仪表盘还没有添加图表，请点击\"添加图表\"按钮添加",
        "chart_added_to_dashboard": "图表已添加到仪表盘",
        "chart_already_in_dashboard": "该图表已存在于仪表盘中",
        "data_drill_down_details": "数据下钻详情",
        "back": "返回",
        "close": "关闭",
        "loading_drill_down_data": "正在加载详细数据...",
        "no_data": "无数据",
        "data_details": "数据详情",
        "drill_down_detail_data": "{} = {} 的详细数据",
        "drill_down_records_found": "共找到 {} 条记录（最多显示100条）",
        "drill_down_error": "处理数据下钻时发生错误: {}",
        "cannot_load_original_data": "无法加载原始数据",
        "no_data_points": "无数据点",
        "no_date_field_found": "未找到日期字段，无法应用时间筛选",
        "date_field_conversion_failed": "日期字段转换失败: {}",
        "date_format_error_parse": "日期格式错误: 无法解析日期",
        "date_format_error_timedelta": "日期格式错误: 无法创建时间差",
        "date_format_error": "日期格式错误: {}",
        "custom_range_needs_dates": "自定义时间范围需要指定起始和结束日期",
        "no_valid_date_data": "日期字段中无有效日期数据",
        "time_filter_failed": "时间筛选失败: {}",
        "chart_not_found": "图表不存在",
        "chart_config_loaded": "图表配置已加载，可以开始编辑",
        "load_chart_failed": "加载图表失败：{}",
        "chart_deleted": "图表 '{}' 已删除",
        "delete_failed": "删除失败：{}",
        "datasource_not_found": "数据源不存在",
        "no_fields_detected": "未检测到字段，请检查数据源配置",
        "no_fields_detected_simple": "未检测到字段，请检查数据源",
        "load_fields_failed": "加载字段失败：{}",
        "cannot_load_group_data": "无法加载分组数据",
        "load_group_data_failed": "加载分组数据失败：{}",
        "drag_field_as_column_n": "拖拽字段到此处作为第{}列",
        "drag_field_as_row_n": "拖拽字段到此处作为第{}行",
        "column_n": "第{}列: {}",
        "row_n": "第{}行: {}",
        "data_empty": "数据为空",
        "data_empty_cannot_generate": "数据为空，无法生成图表",
        
        # 仪表盘页面
        "dashboard_title": "仪表盘",
        "select_dashboard": "选择仪表盘",
        "create_dashboard": "创建仪表盘",
        "dashboard_name": "仪表盘名称",
        "dashboard_description": "描述",
        "time_filter": "时间筛选",
        "today": "今天",
        "last_7_days": "近7天",
        "last_30_days": "近30天",
        "last_90_days": "近90天",
        "this_month": "本月",
        "last_month": "上月",
        "custom_range": "自定义范围",
        "export": "导出",
        "refresh": "刷新",
        "my_dashboard": "我的仪表盘",
        "select_or_create_dashboard": "选择或创建仪表盘...",
        "new_dashboard": "新建仪表盘",
        "edit": "编辑",
        "delete": "删除",
        "add_chart": "添加图表",
    },
    "en": {
        # 通用
        "loading": "Loading...",
        "save": "Save",
        "cancel": "Cancel",
        "delete": "Delete",
        "edit": "Edit",
        "add": "Add",
        "close": "Close",
        "confirm": "Confirm",
        "test": "Test",
        "success": "Success",
        "error": "Error",
        "warning": "Warning",
        
        # 侧边栏
        "sidebar_title": "BI Platform",
        "datasource_management": "Datasource Management",
        "chart_designer": "Chart Designer",
        "dashboard": "Dashboard",
        "settings": "Settings",
        "version": "Version",
        "ui_only": "UI Only",
        
        # 设置页面
        "general_settings": "General Settings",
        "auto_refresh_interval": "Auto Refresh Interval",
        "off": "Off",
        "minutes": "minutes",
        "hour": "hour",
        "default_chart_theme": "Default Chart Theme",
        "default": "Default",
        "business_blue": "Business Blue",
        "vibrant_orange": "Vibrant Orange",
        "natural_green": "Natural Green",
        "purple": "Purple",
        "save_settings": "Save Settings",
        "settings_saved": "Settings saved successfully!",
        "datasource_config": "Datasource Configuration",
        "export_config": "Export Configuration",
        "export_all_datasource_config": "Export All Datasource Configurations",
        "import_config": "Import Configuration",
        "import_datasource_config": "Import Datasource Configuration",
        "language_settings": "Language Settings",
        "select_language": "Select Language",
        "chinese": "中文",
        "english": "English",
        "language_changed": "Language changed successfully!",
        
        # 数据源页面
        "datasource_management_title": "Datasource Management",
        "datasource_list": "Datasource List",
        "add_datasource": "+ Add Datasource",
        "upload_file": "Upload File",
        "upload_file_button": "Upload File",
        "supported_formats": "Supports CSV, Excel (.xls, .xlsx)",
        "datasource_name": "Datasource Name",
        "datasource_name_placeholder": "e.g.: Sales Data",
        "local_file": "Local File (CSV/Excel)",
        "database": "Database",
        "rest_api": "REST API",
        "database_type": "Database Type",
        "database_host": "Host",
        "database_port": "Port",
        "database_name": "Database Name",
        "database_user": "Username",
        "database_password": "Password",
        "sql_query": "SQL Query",
        "table_name": "Table Name",
        "api_url": "API URL",
        "request_method": "Request Method",
        "api_headers": "Request Headers (JSON format)",
        "api_params": "Request Parameters (JSON format)",
        "api_name_placeholder": "e.g.: API Datasource",
        "database_name_placeholder": "e.g.: Production Database",
        "test_connection": "Test Connection",
        "connection_success": "Connection successful!",
        "connection_failed": "Connection failed",
        "api_connection_success": "API connection successful!",
        "fill_api_url": "Please fill in API URL",
        "invalid_json_format": "Invalid format, please enter valid JSON",
        "headers_format_error": "Headers format error, please enter valid JSON",
        "params_format_error": "Parameters format error, please enter valid JSON",
        "no_datasource": "No datasources yet, click 'Add Datasource' to add",
        "connected": "Connected",
        "disconnected": "Disconnected",
        "data_preview": "Data Preview",
        "select_datasource_for_preview": "Please select a datasource to view preview",
        "edit_datasource": "Edit Datasource",
        "new_datasource": "Add Datasource",
        "upload_success": "File uploaded successfully!",
        "fill_database_info": "Please fill in complete database information",
        "upload_file_first": "Please upload file first",
        "data_rows_cols": "Data: {} rows × {} columns",
        "fields": "Fields: {}",
        "filename": "Filename",
        "field_info": "Field Information",
        "field_type_numeric": "Numeric",
        "field_type_date": "Date",
        "field_type_text": "Text",
        "operation_failed": "Operation failed",
        "datasource_saved": "Datasource saved successfully!",
        "datasource_deleted": "Datasource deleted",
        "preview_failed": "Preview failed",
        "operation_id_parse_failed": "Failed to parse operation ID",
        "name": "Name",
        "type": "Type",
        "status": "Status",
        "last_updated": "Last Updated",
        "actions": "Actions",
        "database_tab_label": "Database (PostgreSQL/MySQL)",
        
        # 图表设计器页面
        "chart_designer_title": "Chart Designer",
        "select_datasource": "Select Datasource",
        "field_list": "Field List (Draggable)",
        "select_datasource_first": "Please select a datasource to view fields",
        "chart_type": "Chart Type",
        "line_chart": "Line Chart",
        "bar_chart": "Bar Chart",
        "pie_chart": "Pie Chart",
        "table": "Table",
        "combo_chart": "Combo Chart",
        "chart_config": "Chart Configuration",
        "x_axis": "X Axis",
        "y_axis": "Y Axis",
        "group": "Group",
        "chart_title": "Chart Title",
        "color_theme": "Color Theme",
        "show_labels": "Show Labels",
        "show_legend": "Show Legend",
        "aggregation_function": "Aggregation Function",
        "preview": "Preview",
        "save_chart": "Save Chart",
        "clear": "Clear",
        "drag_field_here": "Drag field here",
        "display_orientation": "Display Orientation",
        "horizontal_display": "Horizontal (fields as columns)",
        "vertical_display": "Vertical (fields as rows)",
        "table_columns_config": "Table Columns Configuration",
        "drag_field_to_columns": "Drag fields to the column area below to set table columns",
        "drag_field_as_column": "Drag field here as column {}",
        "add_column": "Add Column",
        "table_rows_config": "Table Rows Configuration",
        "drag_field_to_rows": "Drag fields to the row area below to set table rows",
        "drag_field_as_row": "Drag field here as row {}",
        "add_row": "Add Row",
        "group_color": "Group/Color",
        "aggregation_function_config": "Aggregation Function Configuration",
        "default_aggregation_function": "Default Aggregation Function (for all Y-axis fields)",
        "field_aggregation_function": "Field Aggregation Functions (optional)",
        "field_aggregation_hint": "You can set a separate aggregation function for each Y-axis field. If not set, the default aggregation function will be used.",
        "sum": "Sum (SUM)",
        "avg": "Average (AVG)",
        "count": "Count (COUNT)",
        "max": "Maximum (MAX)",
        "min": "Minimum (MIN)",
        "percentage": "Percentage",
        "style_config": "Style Configuration",
        "enter_chart_title": "Enter chart title",
        "custom_color_config": "Custom Colors (different color for each group)",
        "custom_color_hint": "When there is a grouping field, you can set custom colors for each group. Colors will automatically ensure no duplicates.",
        "set_group_field_first": "Please set grouping field first",
        "saved_charts": "Saved Charts",
        "refresh": "Refresh",
        "chart_preview": "Chart Preview",
        "export_image": "Export Image",
        "select_datasource_and_config": "Please select a datasource and configure fields to generate preview",
        "no_saved_charts": "No saved charts yet",
        "unknown": "Unknown",
        "chart_type_colon": "Type: {}",
        "created_colon": "Created: {}",
        "unnamed_chart": "Unnamed Chart",
        "chart": "Chart",
        "drag_field_to_x_axis": "Please drag fields to the X axis",
        "add_y_axis_field_first": "Please add Y-axis fields first",
        "at_least_one_y_axis": "Please select at least one Y-axis field",
        "pie_needs_group_field": "Pie chart requires a group field",
        "pie_needs_numeric_field": "Pie chart requires a numeric field",
        "data_table": "Data Table",
        "chart_saved_success": "Chart saved successfully!",
        "save_chart_failed": "Failed to save chart",
        "new_chart_created": "New chart created, please start configuring",
        "hint_drag_field_below": "Hint: Drag fields to the area below",
        "numeric_field_required": "Numeric Field (Required)",
        "hint_drag_numeric_field": "Hint: Drag numeric fields to the area below",
        "category_field_required": "Category Field (Required)",
        "hint_drag_category_field": "Hint: Drag category fields to the area below",
        "y_axis_label": "Y Axis",
        "group_color_label": "Group/Color",
        "select_datasource_to_view_fields": "Please select a datasource to view fields",
        "select_datasource": "Please select a datasource",
        "drag_field_to_table_columns": "Please drag fields to the table columns area",
        "drag_field_to_table_rows": "Please drag fields to the table rows area",
        "field_not_in_data": "Selected field does not exist in the data",
        "generate_chart_failed": "Failed to generate chart",
        "select_datasource_first": "Please select a datasource first",
        "please_add_datasource_first": "Please add datasource first",
        "loading": "Loading...",
        "filter_mode": "Filter Mode",
        "drill_down_mode": "Drill Down Mode",
        "current_mode_filter": "Current mode: Filter mode - Left-click chart data points to filter other charts",
        "current_mode_drill_down": "Current mode: Drill-down mode - Left-click chart data points to view detailed data",
        "filter_source": "Filter Source",
        "filtered": "Filtered: {}={}",
        "filtering": "Filtering: {} - {}={}",
        "time_filter_no_data": "No data after time filter (filter field: {})",
        "clear_filter": "Clear Filter",
        "share_link": "Share Link",
        "all": "All",
        "start_date": "Start Date",
        "end_date": "End Date",
        "please_select_or_create_dashboard": "Please select or create a dashboard",
        "new_dashboard": "New Dashboard",
        "enter_dashboard_name": "Enter dashboard name",
        "enter_description_optional": "Enter description (optional)",
        "add_chart_to_dashboard": "Add Chart to Dashboard",
        "select_chart": "Select Chart",
        "share_dashboard_link": "Share Dashboard Link",
        "copy_link_to_share": "Copy the link below to share with others. They can directly access this dashboard:",
        "copy": "Copy",
        "tip": "Tip:",
        "share_link_tip": "The shared link contains the current dashboard ID. Visitors will see the same dashboard content.",
        "no_charts_in_dashboard": "This dashboard has no charts yet. Please click the \"Add Chart\" button to add charts.",
        "chart_added_to_dashboard": "Chart added to dashboard",
        "chart_already_in_dashboard": "This chart already exists in the dashboard",
        "data_drill_down_details": "Data Drill Down Details",
        "back": "Back",
        "close": "Close",
        "loading_drill_down_data": "Loading detailed data...",
        "no_data": "No Data",
        "data_details": "Data Details",
        "drill_down_detail_data": "Detailed data for {} = {}",
        "drill_down_records_found": "Found {} records (showing up to 100)",
        "drill_down_error": "Error processing drill-down: {}",
        "cannot_load_original_data": "Cannot load original data",
        "no_data_points": "No data points",
        "no_date_field_found": "No date field found, unable to apply time filter",
        "date_field_conversion_failed": "Date field conversion failed: {}",
        "date_format_error_parse": "Date format error: Unable to parse date",
        "date_format_error_timedelta": "Date format error: Unable to create time delta",
        "date_format_error": "Date format error: {}",
        "custom_range_needs_dates": "Custom time range requires start and end dates",
        "no_valid_date_data": "No valid date data in date field",
        "time_filter_failed": "Time filter failed: {}",
        "chart_not_found": "Chart not found",
        "chart_config_loaded": "Chart configuration loaded, you can start editing",
        "load_chart_failed": "Failed to load chart: {}",
        "chart_deleted": "Chart '{}' has been deleted",
        "delete_failed": "Delete failed: {}",
        "datasource_not_found": "Datasource not found",
        "no_fields_detected": "No fields detected, please check datasource configuration",
        "no_fields_detected_simple": "No fields detected, please check datasource",
        "load_fields_failed": "Failed to load fields: {}",
        "cannot_load_group_data": "Cannot load group data",
        "load_group_data_failed": "Failed to load group data: {}",
        "drag_field_as_column_n": "Drag field here as column {}",
        "drag_field_as_row_n": "Drag field here as row {}",
        "column_n": "Column {}: {}",
        "row_n": "Row {}: {}",
        "data_empty": "Data is empty",
        "data_empty_cannot_generate": "Data is empty, cannot generate chart",
        
        # 仪表盘页面
        "dashboard_title": "Dashboard",
        "select_dashboard": "Select Dashboard",
        "create_dashboard": "Create Dashboard",
        "dashboard_name": "Dashboard Name",
        "dashboard_description": "Description",
        "time_filter": "Time Filter",
        "today": "Today",
        "last_7_days": "Last 7 Days",
        "last_30_days": "Last 30 Days",
        "last_90_days": "Last 90 Days",
        "this_month": "This Month",
        "last_month": "Last Month",
        "custom_range": "Custom Range",
        "export": "Export",
        "refresh": "Refresh",
        "my_dashboard": "My Dashboard",
        "select_or_create_dashboard": "Select or create dashboard...",
        "new_dashboard": "New Dashboard",
        "edit": "Edit",
        "delete": "Delete",
        "add_chart": "Add Chart",
    }
}


class LanguageManager:
    """语言管理器"""
    
    def __init__(self):
        """初始化语言管理器"""
        self.config_file = LANGUAGE_CONFIG_FILE
        self.config_file.parent.mkdir(exist_ok=True)
        self._current_language = self.load_language()
    
    def load_language(self) -> str:
        """从配置文件加载语言设置"""
        if self.config_file.exists():
            try:
                with open(self.config_file, 'r', encoding='utf-8') as f:
                    config = json.load(f)
                    lang = config.get('language', DEFAULT_LANGUAGE)
                    return lang
            except Exception as e:
                logger.error(f"加载语言配置失败: {e}", exc_info=True)
                return DEFAULT_LANGUAGE
        return DEFAULT_LANGUAGE
    
    def save_language(self, language: str) -> bool:
        """保存语言设置到配置文件"""
        try:
            config = {'language': language}
            with open(self.config_file, 'w', encoding='utf-8') as f:
                json.dump(config, f, indent=2, ensure_ascii=False)
            self._current_language = language
            return True
        except Exception as e:
            logger.error(f"保存语言配置失败: {e}", exc_info=True)
            return False
    
    def set_language(self, language: str) -> None:
        """设置当前语言（不保存到文件，仅更新内存中的值）"""
        if language in LANGUAGE_TEXTS:
            self._current_language = language
    
    def get_language(self) -> str:
        """获取当前语言"""
        return self._current_language
    
    def get_text(self, key: str, language: Optional[str] = None) -> str:
        """获取指定语言的文本"""
        lang = language or self._current_language
        return LANGUAGE_TEXTS.get(lang, LANGUAGE_TEXTS[DEFAULT_LANGUAGE]).get(key, key)
    
    def get_all_texts(self, language: Optional[str] = None) -> Dict[str, str]:
        """获取指定语言的所有文本"""
        lang = language or self._current_language
        return LANGUAGE_TEXTS.get(lang, LANGUAGE_TEXTS[DEFAULT_LANGUAGE])


# 全局语言管理器实例
language_manager = LanguageManager()

